--- 
# Write a playbook to deploy the file ‘/tmp/system_info’ on all hosts except for controllers group, with the following content:
# I'm <HOSTNAME> and my operating system is <OS>
- name: Deploy /tmp/system_info file
  hosts: all:!controllers
  tasks: 
      - name: Deploy /tmp/system_info
        template:
            src: system_info.j2 
            dest: /tmp/system_info