---
# tasks file for flaskweb
  tasks:
    - name: Install Python flask dependencies
      pip: name='{{ item }}' state=present
      with_items:
        - flask
        - flask-mysql

    - name: Copy source code
      git:
        src: 'https://github.com/mmumshad/simple-webapp.git'
        dest: /opt/project-web

    - name: Print command
      debug: msg="MYSQL_DATABASE_HOST={{ hostvars[groups['db_servers'][0]]['private_ip'] }} FLASK_APP=/opt/project-web/app.py nohup flask run --host=0.0.0.0 --port=80 &"

    - name: Start Web Server
      shell: MYSQL_DATABASE_HOST={{ hostvars[groups['db_servers'][0]]['private_ip'] }} FLASK_APP=/opt/project-web/app.py nohup flask run --host=0.0.0.0 --port=80 &
