#!/bin/bash

# Check if we're debugging
if [[ $1 != DEBUG ]]
then
  if (( $# < 2 ))
  then
    echo "SYNTAX: $0 <ENV> <SSHKEY>" 1>&2
    exit 1
  fi
  ansibleENV="$1"
	sshKeyFile="$2"
else
  if (( $# < 3 ))
  then
    echo "SYNTAX: $0 DEBUG <ENV> <SSHKEY>" 1>&2
    exit 1
  fi
  ansibleENV="$2"
	sshKeyFile="$3"
fi

# Check if the key file supplied exists
if [[ ! -e $sshKeyFile ]] || [[ -z $sshKeyFile ]]
then
	echo "SSH Key file $sshKeyFile does not exist, or not supplied" 1>&2
	echo "SYNTAX: $0 [DEBUG] <ENV> <SSHKEY>"
	exit 1
fi

if [[ $1 == DEBUG ]]
then
	ansible-playbook -vvvv -i environments/$ansibleENV --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
else
	ansible-playbook -i environments/$ansibleENV --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
fi
