#!/bin/bash

if (( $# < 1 ))
then
  echo "SYNTAX: $0 <ENV>" 1>&2
  exit 1
fi

ansibleENV=$1

ansible-playbook -i environments/$ansibleENV --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" remove.yml
